import { createClient } from '@supabase/supabase-js'
import Link from 'next/link'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

export default async function ToolPage({ params }: { params: { slug: string } }) {
  // Case-insensitive search using .ilike
  const { data: tool, error } = await supabase
    .from('ai_tools')
    .select('*')
    .ilike('slug', params.slug) 
    .single()

  if (!tool) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-10">
        <h1 className="text-4xl font-bold text-gray-800">404</h1>
        <p className="text-gray-500 mt-2">Tool '{params.slug}' not found in the Vault.</p>
        <Link href="/" className="mt-6 text-blue-600 hover:underline">← Back to Directory</Link>
      </div>
    )
  }

  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12 bg-white min-h-screen">
      <Link href="/" className="text-blue-500 font-medium hover:underline mb-8 inline-block">
        ← Back to Vault
      </Link>
      
      <header className="border-b border-gray-100 pb-8">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-blue-600 font-bold text-sm uppercase tracking-widest mb-2">
              {tool.category}
            </p>
            <h1 className="text-5xl font-black text-gray-900 leading-tight">
              {tool.name}
            </h1>
          </div>
        </div>
      </header>

      <div className="mt-10">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">AI Expert Review</h2>
        <div className="leading-relaxed text-gray-700 text-lg whitespace-pre-wrap">
          {tool.description}
        </div>
      </div>

      <div className="mt-12 p-8 bg-blue-50 rounded-3xl border border-blue-100">
        <h3 className="text-xl font-bold text-blue-900 mb-2">Ready to try {tool.name}?</h3>
        <p className="text-blue-700 mb-6 text-sm">Visit the official website to start using this tool today.</p>
        <a 
          href={tool.website_url} 
          target="_blank" 
          rel="noopener noreferrer"
          className="inline-block bg-blue-600 text-white px-8 py-4 rounded-2xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-200"
        >
          Visit Official Website →
        </a>
      </div>

      <footer className="mt-20 pt-10 border-t border-gray-50 text-center text-gray-400 text-sm">
        Review generated by AIVault Engine v2.0
      </footer>
    </div>
  )
}
