import { createClient } from '@supabase/supabase-js'
import Link from 'next/link'
import { Metadata } from 'next'

// Supabase Setup
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

// 1. DYNAMIC SEO METADATA (Google Search ke liye)
export async function generateMetadata({ params }: { params: any }): Promise<Metadata> {
  const { slug } = await params;
  const { data: tool } = await supabase
    .from('ai_tools')
    .select('name, category')
    .ilike('slug', slug)
    .single();

  if (!tool) return { title: 'Tool Not Found - AIVault' };

  return {
    title: `${tool.name} Review 2026: Best AI for ${tool.category} | AIVault`,
    description: `Expert review of ${tool.name}. Learn about its key features, pricing, and benefits. The ultimate guide for ${tool.category} AI tools.`,
    openGraph: {
      title: `${tool.name} - AIVault AI Directory`,
      description: `Discover how ${tool.name} is transforming ${tool.category}.`,
      type: 'website',
    }
  }
}

// 2. MAIN PAGE COMPONENT
export default async function ToolPage({ params }: { params: Promise<{ slug: string }> }) {
  const resolvedParams = await params;
  const toolSlug = resolvedParams.slug;

  const { data: tool } = await supabase
    .from('ai_tools')
    .select('*')
    .ilike('slug', toolSlug)
    .maybeSingle();

  if (!tool) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center p-10 text-center">
        <h1 className="text-6xl font-bold text-gray-200 uppercase">404</h1>
        <p className="text-gray-600 mt-4 italic">"{toolSlug}" humare vault mein nahi hai.</p>
        <Link href="/" className="mt-8 bg-blue-600 text-white px-8 py-3 rounded-xl font-bold">← Go Back Home</Link>
      </div>
    );
  }

  // GOOGLE SCHEMA (JSON-LD) - Isse Google aapke tool ko 'Software' category mein index karega
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": tool.name,
    "applicationCategory": tool.category,
    "operatingSystem": "Web-based",
    "description": tool.description.substring(0, 160),
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "4.8",
      "reviewCount": "89"
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12 min-h-screen">
      {/* Schema Injection for Google Bots */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <nav className="mb-10">
        <Link href="/" className="text-blue-600 font-bold flex items-center gap-2 hover:opacity-70">
          <span>←</span> Back to AIVault
        </Link>
      </nav>

      <header className="border-b border-gray-100 pb-10">
        <div className="inline-block bg-blue-50 text-blue-700 px-4 py-1 rounded-full text-xs font-black uppercase tracking-widest mb-4">
          {tool.category}
        </div>
        <h1 className="text-5xl md:text-7xl font-black text-gray-900 tracking-tighter">
          {tool.name}
        </h1>
      </header>

      <main className="mt-12">
        <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-2">
          <span className="w-2 h-8 bg-blue-600 rounded-full"></span>
          Expert Analysis & Review
        </h2>
        <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed whitespace-pre-wrap font-medium">
          {tool.description}
        </div>
      </main>

      {/* CALL TO ACTION */}
      <section className="mt-16 p-8 md:p-12 bg-gray-900 rounded-[2.5rem] text-white shadow-2xl relative overflow-hidden">
        <div className="relative z-10">
          <h3 className="text-3xl font-black mb-4 italic">Ready to use {tool.name}?</h3>
          <p className="text-gray-400 mb-8 text-lg">Don't wait. Start your AI journey with this tool today.</p>
          <a
            href={tool.website_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center justify-center bg-blue-600 text-white px-10 py-5 rounded-2xl font-black text-xl hover:bg-blue-500 hover:scale-105 transition-all w-full md:w-auto"
          >
            Visit Official Website ↗
          </a>
        </div>
        <div className="absolute -right-20 -bottom-20 w-80 h-80 bg-blue-600 opacity-20 rounded-full blur-3xl"></div>
      </section>

      <footer className="mt-24 py-10 border-t border-gray-50 text-center text-gray-400 text-sm">
        &copy; 2026 AIVault Engine. All reviews are generated by AI for educational purposes.
      </footer>
    </div>
  );
}
